### ISSUE TITLE
PDK docker latest tag is not getting updated on Dockerhub

### ISSUE THREAD

**Issue by geoffdavis** [puppetlabs/pdk-docker#36]
## Describe the Bug
The image tagged with latest on Dockerhub is pointing to a 7 month old version of the container with only PDK version 2.2 in it.
https://hub.docker.com/r/puppet/pdk/tags

Version sha256:f9891f0db968fc270c11e36f14f2823911d128a1ed4af996d303ebb0cc9c423f was last pushed by pdkbot on September 2, 2021

There is also no 2.3.0.0 tag available on hub.docker.com, or in this repository.

## Expected Behavior
The latest tag on hub.docker.com should point to the most recent release version. This repository should have a tag for version 2.3.0.0 and possibly 2.4.0.0

## Steps to Reproduce
1. Go to '[this repository's tags page](https://github.com/puppetlabs/pdk-docker/tags)'
2. Verify no tag for 2.3.0.0
3. Go to https://hub.docker.com/r/puppet/pdk/tags
4. Verify latest is 7 months old.

## Environment
 - All
 - All
 
## Additional Context
Running PDK in a devcontainer in VScode results in all sorts of garbage resulting from this bug: https://tickets.puppetlabs.com/browse/PUP-11196

This is fixed in Puppet 6.25 but ye olde PDK doesn't have that version.

**Comment by chelnak** [comment]
Thanks for letting us know @geoffdavis! We will investigate and get back to you soon!

**Comment by chelnak** [comment]
Hey @geoffdavis, we are about to cut a new release of PDK so this will hopefully be repo next week or at very least we will have a clear understanding about why latest isn't getting updated.

Thanks for your patience!

**Comment by chelnak** [comment]
Hey @geoffdavis , The latest tag should now reflect the most up to date PDK version!

```
docker run puppet/pdk --version
2.5.0
```

**Comment by geoffdavis** [comment]
Circling back to confirm this worked. Thanks!
