### ISSUE TITLE
Gems installs broken since about 2.6.0.0

### ISSUE THREAD

**Issue by billglick** [puppetlabs/pdk-docker#43]
## Describe the Bug
Starting around 2023-01-19 (presumably with PDK Docker image [2.6.0.0](https://github.com/puppetlabs/pdk-docker/releases/tag/2.6.0.0) ) the PDK docker image does not have `make` or `gcc` packages and so `gem install` fails (when pdk attempts to install dependencies).

## Expected Behavior
Prior to this we could `gem install` dependencies.

## Steps to Reproduce
TBD

## Environment
 - Version: 2.6.1.0
 - Platform: ubuntu-latest

## Additional Context
We run into this when running the [puppets-epic-show-theatre/action-pdk-validate](https://github.com/puppets-epic-show-theatre/action-pdk-validate) GitHub action. We [originally](https://github.com/puppets-epic-show-theatre/action-pdk-validate/issues/3) thought it was an issue with that action, but it seems to be due to a change of either the PDK and/or ubuntu-latest Docker images.

We are able to work around this by installing `build-essential` package group in the container and then the pdk validate succeeds.

**Comment by billglick** [comment]
@chelnak That sounds very promising.

Unfortunately I do not know how to build and test an image from a pull request. Is there a standard process that I could follow to do that?

**Comment by andylytical** [comment]
@chelnak `pdk` still fails with #42 

Working with @billglick, here's the steps to reproduce (and also to verify the workaround): https://github.com/andylytical/pdktest

**Comment by chelnak** [comment]
Thanks, I'll take a look.

**Comment by chelnak** [comment]
I think your issue might be pdk-templates here.

I noticed that the module you use as an example is pinned to pdk-templates 2.5.0.

There were some significant changes with gems between 2.5 and 2.6.

After running `pdk update --force` in your module I was able to perform a successful validation.

Can you give this a try?

**Comment by chelnak** [comment]
So #42 really just updates the base image and ensures that we have some dependencies available.

It sounds like you could just pull  the 2.5 tag here though?

https://hub.docker.com/layers/puppet/pdk/2.5.0.0/images/sha256-87ed6a61199feb968cf0f53302c6c94e93170a4c193b0e6f945c3e3c01bbbbd2?context=explore

**Comment by fraenki** [comment]
> It sounds like you could just pull the 2.5 tag here though?

Sure. :) I wanted to avoid that, so that it doesn't break when I'm actually upgrading my modules to PDK >= 2.6... but yes, it's a valid workaround.

**Comment by chelnak** [comment]
Yeah so I think this is a limitation of the docket container.

You'd have to upgrade on a module by module basis.

**Comment by andylytical** [comment]
I confirmed this fixes the issue!

@billglick do you agree?

**Comment by andylytical** [comment]
@chelnak Feel free to close this issue.

**Comment by chelnak** [comment]
Thank you 🙏
