### ISSUE TITLE
Where is PDK_RELEASE_TYPE used?

### ISSUE THREAD

**Issue by rwaffen** [puppetlabs/pdk-docker#56]
## Describe the Change You Would Like
Where is PDK_RELEASE_TYPE used and what does it do?

```
$ grep -r PDK_RELEASE_TYPE
update-pdk-release-file.rb:  release_file.puts "export PDK_RELEASE_TYPE=\"#{pdk_latest[:type]}\""
pdk-release.env:export PDK_RELEASE_TYPE="release"
```

**Comment by h0tw1r3** [comment]
The update-pdk-release.rb is used as part of our Jenkins release pipeline.
PDK_RELEASE_TYPE is not currently used. It was intended to support building docker images with the nightly pdk packages.

**Comment by rwaffen** [comment]
okay. thx for clarification :)
