### ISSUE TITLE
Current nightly, latest, and 3.2.0.1 images are linux/arm64 only

### ISSUE THREAD

**Issue by jaevans** [puppetlabs/pdk-docker#63]
## Describe the Bug

Containers no longer run on x86_64 based CPUs

## Expected Behavior

Container works correctly for x86_64 and arm64 CPUs

## Steps to Reproduce
1. docker run -it --rm -v $PWD:/root puppet/pdk:3.2.0.1 validate

## Environment
 - Version 3.2.0.1
 - Platform Ubuntu (private github runner, I'm not quite sure of the version)

## Additional Context

Works great on M1 macs, I only noticed when moving to CI.

**Comment by gavindidrichsen** [comment]
Hi @jaevans.  This should be fixed now.  There are now [2 pdk architectures](https://hub.docker.com/layers/puppet/pdk/3.2.0.1/images/sha256-a2b6c0d5418307c2acf367245f69c35a332e712b16836bbb071f740785ea8bf3?context=explore) arm and amd present:

![image](https://github.com/puppetlabs/pdk-docker/assets/16652757/e5a186db-4ea3-45df-892a-36d2653b582e)
