### ISSUE TITLE
PDK Image does not include ssh

### ISSUE THREAD

**Issue by alanraison** [puppetlabs/pdk-docker#7]
## Describe the Bug
`pdk test unit` with fixtures in Git repositories with ssh transport fails, since ssh is missing from the image.

## Expected Behavior
`pdk test unit` downloads module dependencies correctly.

## Steps to Reproduce
```
docker run --rm -ti --entrypoint bash puppet/pdk
root@13433331dd62:~# git clone ssh://git@#####/%%%%%.git
Cloning into '%%%%%'...
fatal: cannot run ssh: No such file or directory
fatal: unable to fork
```

## Environment
 - Version puppet/pdk@sha256:1dc1844efd3e9db7e5f5f2040fc0e49d319d9297f1369ea9ff9d6aab002572d8

**Comment by rharrison10** [comment]
Has anyone looked at this bug? It seems that the `pdk` package should already require `openssh-client` and `git` since its a requirement for it to run properly.

**Comment by fraenki** [comment]
@alanraison I've created an issue in Puppetlabs' Jira:
https://tickets.puppetlabs.com/browse/PDK-1668

@alanraison I've seen that you've already fixed this issue in your fork. Could you submit a pull request and add a link in PDK-1668?
